DROP TABLE IF EXISTS ODONTOLOGO ; CREATE TABLE ODONTOLOGO(ID INT AUTO_INCREMENT PRIMARY KEY, NUMEROMATRICULA INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50)NOT NULL)
---para test---

INSERT INTO ODONTOLOGO (NUMEROMATRICULA,NOMBRE,APELLIDO) VALUES(789,'Marco','De Santis'),(124,'Nahuel','Romero')

SELECT*FROM ODONTOLOGO